export const testData = [
  {
    name: "Team",
    playerOne: {
      name: "Player 1 – Full Name",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Player 2 – Full Name",
      id: "",
      uid: "",
      points: 0,
    },
    points: 0,
  },
  {
    name: "Super team A",
    playerOne: {
      name: "Michael Leuwig",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Peter Choi",
      id: "",
      uid: "",
      points: 0,
    },
    points: 0,
  },
  {
    name: "Cabala/Kasan",
    playerOne: {
      name: "Ondra Kasan",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Jaroslav Čabala",
      id: "6426f2596fa0965f30d16743",
      uid: "8i27PMsUGINx6MGx45Ebi121dht1",
      points: 67.5,
    },
    points: 67.5,
  },
  {
    name: "Hustling Brothers",
    playerOne: {
      name: "Levi Vandaele",
      id: "6426f24c6fa0965f30d16570",
      uid: "sv6j5IVRd5O8nPEIkgaZqFEEtBr1",
      points: 625,
    },
    playerTwo: {
      name: "Yosha Vandaele",
      id: "",
      uid: "",
      points: 0,
    },
    points: 625,
  },
  {
    id: "9Q3p4fdR2GOhKTx9U9YZ",
    name: "Eisenträger/Siemer",
    playerOne: {
      id: "6426f24c6fa0965f30d1656c",
      uid: "aoOV5b9nfSZZulDIcpFzPWgYTAz1",
      name: "Eisenträger Lukas",
      points: 375,
    },
    playerTwo: {
      id: "6426f24c6fa0965f30d1656e",
      uid: "7lmgDh8rkqehspl8mnvLXm6n16T2",
      name: "Paul Siemer",
      points: 375,
    },
    points: 750,
  },
  {
    id: "5fKNJPqUfjYLtMD4tSti",
    name: "RCG Powerline",
    playerOne: {
      id: "6426f24c6fa0965f30d16566",
      uid: "UXGUwqawC1WgDzr3aT1Mi1JFrbZ2",
      name: "Benjamin Bachler",
      points: 168.75,
    },
    playerTwo: {
      id: "6426f24c6fa0965f30d16567",
      uid: "5do5IsVNaRT3lRNtEOW2MEdpwq42",
      name: "Nelson Dziruni",
      points: 168.75,
    },
    points: 337.5,
  },
  {
    name: "Pour Combien ?",
    playerOne: {
      name: "Robin Florinda",
      id: "6426f24c6fa0965f30d16569",
      uid: "nFe4GYRECAco9OfjIe6bsgLAf5f1",
      points: 625,
    },
    playerTwo: {
      name: "Dorian Améziane",
      id: "",
      uid: "",
      points: 0,
    },
    points: 625,
  },
  {
    id: "WxOXdf5ahsQcCLXqGjyc",
    name: "nerds in disguise",
    playerOne: {
      id: "6426f24c6fa0965f30d16588",
      uid: "r3F6ZYgNpZdZyUe9BM6hULSR5mb2",
      name: "Stefan Handschmann",
      points: 67.5,
    },
    playerTwo: {
      id: "6426f24c6fa0965f30d16589",
      uid: "2ICUPQEXF9XF1BvLaLc7zXrRYv13",
      name: "David Jindra",
      points: 67.5,
    },
    points: 135,
  },
  {
    name: "Czech this swede",
    playerOne: {
      name: "Ondřej Čejka",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Esaja Ekman",
      id: "",
      uid: "",
      points: 0,
    },
    points: 0,
  },
  {
    name: "Pierre Feuille Victor",
    playerOne: {
      name: "Aymeric Sandoz",
      id: "642c6ad23900f67ce3c736de",
      uid: "la0U4VVXRNMWcK5HPPz0OwCWaJ22",
      points: 84.375,
    },
    playerTwo: {
      name: "Pierre Lecrosnier",
      id: "",
      uid: "",
      points: 0,
    },
    points: 84.375,
  },
  {
    name: "Paindrops",
    playerOne: {
      name: "Yvo Heinen",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Markus Anderle",
      id: "6426f24c6fa0965f30d16579",
      uid: "dFp8bkzUHohQcmNyVOqcfLHbZym2",
      points: 58.75,
    },
    points: 58.75,
  },
  {
    name: "Rainbow Warriors",
    playerOne: {
      name: "Fabian Claus",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Josha Lauterbach",
      id: "",
      uid: "",
      points: 0,
    },
    points: 0,
  },
  {
    name: "Christiani/Krehle",
    playerOne: {
      name: "Lucas Christiani",
      id: "642c6ad23900f67ce3c736d6",
      uid: "9yz884VeQ8PHohA7AZmNZiGsZN53",
      points: 109.375,
    },
    playerTwo: {
      name: "Julian Krehle",
      id: "642b05bb3900f67ce3c631a3",
      uid: "qRCxY54RySM8OcbdWXr2f8OcHHE2",
      points: 109.375,
    },
    points: 218.75,
  },
  {
    name: "Hors Service",
    playerOne: {
      name: "Hugo Lacombe",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Samy Caux-Ramon",
      id: "",
      uid: "",
      points: 0,
    },
    points: 0,
  },
  {
    name: "Widin/Borsoti",
    playerOne: {
      name: "Cedric Widin",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Andrea Borsotti",
      id: "6426f24c6fa0965f30d16583",
      uid: "BhUbDD8tObf6YzdqYRQnDlywRLt1",
      points: 67.5,
    },
    points: 67.5,
  },
  {
    name: "Synchronized",
    playerOne: {
      name: "Gabriel Stoisser",
      id: "6426f24c6fa0965f30d1659a",
      uid: "E5p8Ldd3dhaWez2kK0XvHISZbTr2",
      points: 131.25,
    },
    playerTwo: {
      name: "Jeremey Gaugnon",
      id: "",
      uid: "",
      points: 0,
    },
    points: 131.25,
  },
  {
    name: "Kandula/Visek",
    playerOne: {
      name: "Ravi Kandula",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Jakub Víšek",
      id: "6426f2596fa0965f30d16734",
      uid: "bP3N5or3yyPAlb2GXu5TN1QW7KE2",
      points: 43.4375,
    },
    points: 43.4375,
  },
  {
    name: "Kanis/Sandoy",
    playerOne: {
      name: "Aymeric Sandoz",
      id: "642c6ad23900f67ce3c736de",
      uid: "la0U4VVXRNMWcK5HPPz0OwCWaJ22",
      points: 84.375,
    },
    playerTwo: {
      name: "Peer Kanis",
      id: "",
      uid: "",
      points: 0,
    },
    points: 84.375,
  },
  {
    name: "Laurin/Mathieu",
    playerOne: {
      name: "Olivier Laurin",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Vincent Mathieu",
      id: "642c6ad23900f67ce3c736c7",
      uid: "fQbRQwEPmgSiDJibCFBlAQUihcN2",
      points: 63.75,
    },
    points: 63.75,
  },
  {
    name: "Bazzani/Gronebaum",
    playerOne: {
      name: "Nicola Bazzani",
      id: "6426f2666fa0965f30d16954",
      uid: "ekg6w4M4PeVh6NABzQqYRUCs61B2",
      points: 67.5,
    },
    playerTwo: {
      name: "Emil Grönebaum",
      id: "",
      uid: "",
      points: 0,
    },
    points: 67.5,
  },
  {
    name: "Prufer/Merca",
    playerOne: {
      name: "Rasmus Prüfer",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "ricardo mercadini",
      id: "",
      uid: "",
      points: 0,
    },
    points: 0,
  },
  {
    name: "klinger/ruiz",
    playerOne: {
      name: "Jonas klinger",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Marco Navío Ruiz",
      id: "",
      uid: "",
      points: 0,
    },
    points: 0,
  },
  {
    name: "Tapken/Berlanda",
    playerOne: {
      name: "Lukas Tapken",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Michele Berlanda",
      id: "",
      uid: "",
      points: 0,
    },
    points: 0,
  },
  {
    name: "2nd swedish team",
    playerOne: {
      name: "Herman Henström",
      id: "",
      uid: "",
      points: 0,
    },
    playerTwo: {
      name: "Samuel Mjönes",
      id: "",
      uid: "",
      points: 0,
    },
    points: 0,
  },
];
