/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const TournamentDrawLazyImport = createFileRoute('/tournament-draw')()
const RankingsLazyImport = createFileRoute('/rankings')()
const AboutLazyImport = createFileRoute('/about')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const TournamentDrawLazyRoute = TournamentDrawLazyImport.update({
  path: '/tournament-draw',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/tournament-draw.lazy').then((d) => d.Route),
)

const RankingsLazyRoute = RankingsLazyImport.update({
  path: '/rankings',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/rankings.lazy').then((d) => d.Route))

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/rankings': {
      preLoaderRoute: typeof RankingsLazyImport
      parentRoute: typeof rootRoute
    }
    '/tournament-draw': {
      preLoaderRoute: typeof TournamentDrawLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  AboutLazyRoute,
  RankingsLazyRoute,
  TournamentDrawLazyRoute,
])

/* prettier-ignore-end */
